### PR TITLE
Instruction changes

### PR DESCRIPTION
**Pull request by Ew-Developer**
Changes to the function doinstruction, and the instructions setindex, logtxt and setstr.

I have not tested if these work or not, but they should.

### CODE REVIEW

**Comment by raymonable** [comment]
no

**Comment by Ew-Developer** [comment]
> no

:(

**Comment by headsmasher8557** [comment]
logtxt is supposed to print one string, not a sequence of strings.

also every instruction is considered valid

**Comment by raymonable** [comment]
> logtxt is supposed to print one string, not a sequence of strings.
> 
> also every instruction is considered valid (even if it does not exist)

in other words:
`i hate you because you're a require user and i hate feedback from require users like you`

**Pull request closed without merging**
